Update attributes (update version + download url) and replace init-script.

diff --git a/templates/default/init.sh.erb b/templates/default/init.sh.erb
--- a/templates/default/init.sh.erb
+++ b/templates/default/init.sh.erb
@@ -1,89 +1,63 @@
-#!/bin/sh
-#
-# Simple Redis init.d script conceived to work on Linux systems
-# as it does use of the /proc filesystem.
-#
-# This file is managed by chef, any changes are likely to be lost.
+#! /bin/sh
+### BEGIN INIT INFO
+# Provides:		redis-server
+# Required-Start:	$syslog
+# Required-Stop:	$syslog
+# Should-Start:		$local_fs
+# Should-Stop:		$local_fs
+# Default-Start:	2 3 4 5
+# Default-Stop:		0 1 6
+# Short-Description:	redis-server - Persistent key-value db
+# Description:		redis-server - Persistent key-value db
+### END INIT INFO
+ 
+NAME=redis-server
+DESC=redis-server
 
-EXEC=/usr/local/bin/redis-server
-CLIEXEC=/usr/local/bin/redis-cli
-
+PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
+DAEMON=/usr/bin/redis-server
+DAEMON_ARGS="<%= node[:redis][:config_path] %>"
 PIDFILE="<%= node[:redis][:pidfile] %>"
-REDIS_HOST="<%= node[:redis][:bind] %>"
-REDIS_PORT="<%= node[:redis][:port] %>"
-REDIS_PASSWORD="<%= node[:redis][:password] ? "-a #{node[:redis][:password]}" : "" %>"
-CONF="<%= node[:redis][:config_path] %>"
 
-startRedis()
-{
-  statusRedis
-  STATUS=$?
-  if [ $STATUS -eq 3 ] || [ $STATUS -eq 1 ]
-  then
-    echo "[Action]: Starting Redis server..."
-    $EXEC $CONF
-    sleep 1
-    statusRedis
-  fi
-}
-
-stopRedis()
-{
-  statusRedis
-  if [ $? -eq 0 ]
-  then
-    PID=$(cat $PIDFILE)
-    echo "[Action]: Stopping ..."
-    $CLIEXEC -h $REDIS_HOST -p $REDIS_PORT $REDIS_PASSWORD shutdown
-    while [ -x /proc/${PID} ]
-    do
-      echo "Waiting for Redis to shutdown ..."
-      sleep 1
-    done
-    echo "Redis stopped"
-  fi
-}
-
-statusRedis()
-{
-  if [ ! -f $PIDFILE ]
-  then
-    if [ `ps aux | grep redis | grep $CONF | wc -l` -gt 1 ]
-    then
-      echo "[Status]: There is a redis process running, but no PID file"
-      return 4
-    else
-      echo "[Status]: PID file '$PIDFILE' does not exist, process is not running"
-      return 3
-    fi
-  else
-    PID=$(cat $PIDFILE)
-    if [ `ps aux | grep redis | grep $CONF | grep $PID | wc -l` -gt 0 ]
-    then
-      echo "[Status]: Running with PID $PID and config '$CONF'"
-      return 0
-    else
-      echo "[Status]: Redis is not running, but PID file '$PIDFILE' exists"
-      return 1
-    fi
-  fi
-}
-
+REDIS_USER="<%= node[:redis][:source][:user] ? node[:redis][:source][:user] : "redis" %>"
+REDIS_GROUP="<%= node[:redis][:source][:group] ? node[:redis][:source][:group] : "redis" %>"
+ 
+test -x $DAEMON || exit 0
+test -x $DAEMONBOOTSTRAP || exit 0
+ 
+set -e
+ 
 case "$1" in
-    start)
-        startRedis
-        ;;
-    stop)
-        stopRedis
-        ;;
-    restart)
-        stopRedis
-        startRedis
-        ;;
-    status)
-        statusRedis
-        ;;
-    *)
-        echo "Please use start | stop | restart | status as first argument"
-        ;;
+  start)
+	echo -n "Starting $DESC: "
+	touch $PIDFILE
+	chown redis:redis $PIDFILE
+	if start-stop-daemon --start --quiet --umask 007 --pidfile $PIDFILE --chuid $REDIS_USER:$REDIS_GROUP --exec $DAEMON -- $DAEMON_ARGS
+	then
+		echo "$NAME."
+	else
+		echo "failed"
+	fi
+	;;
+  stop)
+	echo -n "Stopping $DESC: "
+	if start-stop-daemon --stop --retry 10 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
+	then
+		echo "$NAME."
+	else
+		echo "failed"
+	fi
+	rm -f $PIDFILE
+	;;
+ 
+  restart|force-reload)
+	${0} stop
+	${0} start
+	;;
+  *)
+	echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
+	exit 1
+	;;
 esac
+ 
+exit 0
